---
title: "Resources"
---

## Class-related GitHub repos

- [Jupyter notebook resources](https://github.com/psu-psychology/jupyter-resources)
- [Shiny resources](https://github.com/psu-psychology/shiny-resources)
- [R Markdown ioslides resources](https://github.com/psu-psychology/rmarkdown-ioslides)
- [Websites in R Markdown](https://github.com/psu-psychology/rmarkdown-website-template)
- [jsPsych resources](https://github.com/psu-psychology/jsPsych-resources)

## How-to's

- How to [connect to Penn State's RStudio Server Pro](how_to/rstudio-server-pro.html) instance to run RStudio in the cloud.
- How to [connect to Penn State's Jupyter notebook server](how_to/jupyter-notebooks-psu.html).
- How to [use Google's colaboratory Jupyter notebook service](how_to/google-colaboratory.html).

## Web courses

- [RStudio.conf](https://rstudio.com/conference/)
    - [GitHub repo for 2020 conference](https://github.com/rstudio/rstudio-conf)
- [Data Carpentry](https://datacarpentry.org/), now [The Carpentries](https://carpentries.org/)
    - [OpenRefine for Social Science Data](https://datacarpentry.org/openrefine-socialsci/) by Data Carpentry.
    - [R for Reproducible Scientific Analysis](http://swcarpentry.github.io/r-novice-gapminder/)
    - [Programming with Python](http://swcarpentry.github.io/python-novice-inflammation/)
    - [Plotting and Programming in Python](http://swcarpentry.github.io/python-novice-gapminder/)
    - [Version Control with Git](http://swcarpentry.github.io/git-novice/)
    
## Books and E-Books

- Chang, W. (2012). *R Graphics Cookbook*. <http://ase.tufts.edu/bugs/guide/assets/R%20Graphics%20Cookbook.pdf>
- Gandrud, C. (2015). *Reproducible Research with R and R Studio, Second Edition*. CRC Press. <https://www.crcpress.com/Reproducible-Research-with-R-and-R-Studio-Second-Edition/Gandrud/p/book/9781498715379>
- VanderPlas, J. (2016). *Python Data Science Handbook*. <https://jakevdp.github.io/PythonDataScienceHandbook/>
- Wickham, H. & Grolemund, G. (2016). *R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*. O'Reilly Media. <http://shop.oreilly.com/product/0636920034407.do>.
- Wickham, H. (2019). *Advanced R, 2nd Ed*. Chapman & Hall/CRC. <https://adv-r.hadley.nz/>. 
- Xie, Y., Allaire, J.J., & Grolemund, G. (2019). *R Markdown: The Definitive Guide*. Chapman & Hall/CRC. <https://bookdown.org/yihui/rmarkdown/>.

## Blogs/Projects

- R bloggers <https://www.r-bloggers.com/>
- Open science in practice. <https://inattentionalcoffee.wordpress.com/2017/01/03/open-science-in-practice/>
- Practicing what I preach: The open Ph.D. experiment. <http://www.librarianinthecity.com/2016/12/practicing-what-i-preach-the-open-phd-experiment/>
- [Open Stats Lab](https://sites.trinity.edu/osl). Use data published with psychology papers to teach statistics.
- Jupyter, Zeppelin, Beaker: The Rise of the Notebooks. <https://opendatascience.com/blog/jupyter-zeppelin-beaker-the-rise-of-the-notebooks/>
- Open science and free culture. <http://www.simoncolumbus.com/publications-2/open-science-and-free-culture/>
- [Collaborative Replications and Education Project (CREP)](https://osf.io/wfc6u/).

## Software tools

- OpenRefine, <https://openrefine.org>
- LaTeX on the web
    - ShareLaTex <http://sharelatex.com>
    - Overleaf <http://www.overleaf.com>
    - Authorea <http://www.authorea.com>
- Experimental Design Assistant for planning animal studies <https://eda.nc3rs.org.uk/>
- p-hacker Shiny app <http://shinyapps.org/apps/p-hacker/>

## Articles

- Schweinsberg, M., Madan, N., Vianello, M., Sommer, S. A., Jordan, J., Tierney, W., … Uhlmann, E. L. (2016). The pipeline project: Pre-publication independent replications of a single laboratory’s research pipeline. Journal of Experimental Social Psychology, 66, 55–67. <https://doi.org/10.1016/j.jesp.2015.10.001>
- Munafò, M. R., Nosek, B. A., Bishop, D. V. M., Button, K. S., Chambers, C. D., Sert, N. P. du, … Ioannidis, J. P. A. (2017). A manifesto for reproducible science. Nature Human Behaviour, 1, 0021. <https://doi.org/10.1038/s41562-016-0021>.
- Poldrack, R. A., Baker, C. I., Durnez, J., Gorgolewski, K. J., Matthews, P. M., Munafò, M. R., … Yarkoni, T. (2017). Scanning the horizon: towards transparent and reproducible neuroimaging research. Nature Reviews Neuroscience, advance online publication. <https://doi.org/10.1038/nrn.2016.167>.

## Citation Management 

### Comparisons
- <http://guides.lib.uchicago.edu/c.php?g=297307&p=1984557>

- <https://en.wikipedia.org/wiki/Comparison_of_reference_management_software>

### Software

- Mendeley <https://www.mendeley.com/careers/?dgcid=google_paid-search_Mendeley.com-Search-Branded-USA&gclid=Cj0KEQiAifvEBRCVx5up6Ojgr5oBEiQALHw1TviV-SG0qOSpmmSkoIbrYrn1ZvPeZTinianXeiQa6FIaAqA28P8HAQ>
- Zotero <https://www.zotero.org/>
- Paperpile <https://paperpile.com/>
